"""
schemas.py
----------
Defines Pydantic models for request/response validation and serialization.

Pydantic is separate from SQLAlchemy:
  - SQLAlchemy models (models.py) = the database table definition.
  - Pydantic schemas (this file)  = the shape of JSON in API requests/responses.

Why separate? Because what goes in/out of the API is often different from
what's stored in the DB. For example, 'id' and 'created_at' are DB-generated —
the client shouldn't (and can't) set them, but the API should return them.

Naming convention used here:
  - ScanCreate  = body of a POST /scans request (fields the client sends)
  - ScanRead    = a scan record returned by the API (includes all fields)
  - etc.
"""

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, field_validator


# ---------------------------------------------------------------------------
# Shared enums
# ---------------------------------------------------------------------------

class VerdictEnum(str, Enum):
    """
    Restricts the 'verdict' field to exactly two allowed values.
    Using an Enum instead of a plain string means Pydantic will reject
    any other value automatically and return a clear validation error.
    """
    worthy = "worthy"
    not_worthy = "not_worthy"


# ---------------------------------------------------------------------------
# Missing component schema
# ---------------------------------------------------------------------------

class MissingComponent(BaseModel):
    """
    Represents a single missing component detected by the AI/CV model.

    The AI/CV team provides only the component name and how many are missing —
    no coordinates or per-component confidence scores. Extra fields passed in
    the JSON payload are silently ignored, keeping the schema forward-compatible
    (e.g. old payloads that still include x/y/confidence won't cause a 422).
    """
    name: str = Field(
        ...,
        min_length=1,
        description="Label / name of the missing component, e.g. 'resistor'.",
        examples=["resistor"],
    )
    count: int = Field(
        ...,
        ge=1,
        description="How many of this component are missing (must be at least 1).",
        examples=[2],
    )

    model_config = {
        # Allow extra fields so old payloads (with x/y/confidence) won't cause
        # Pydantic validation errors — those keys are simply discarded.
        "extra": "ignore",
    }


# ---------------------------------------------------------------------------
# Scan schemas
# ---------------------------------------------------------------------------

class ScanCreate(BaseModel):
    """
    Schema for POST /scans — the body the device/inference script sends.
    Only includes fields that the client provides; id and created_at are
    generated by the server.
    """
    object_type: str = Field(
        ...,  # '...' means this field is required (no default).
        min_length=1,
        max_length=100,
        description="Type of object scanned, e.g. 'PCB'.",
        examples=["PCB"],
    )
    verdict: VerdictEnum = Field(
        ...,
        description="AI model verdict: 'worthy' or 'not_worthy'.",
    )
    confidence: float = Field(
        ...,
        ge=0.0,  # ge = "greater than or equal to"
        le=1.0,  # le = "less than or equal to"
        description="Model confidence score between 0.0 and 1.0.",
        examples=[0.97],
    )
    image_url: Optional[str] = Field(
        default=None,
        description="Optional URL pointing to the scan image.",
        examples=["https://storage.example.com/scans/abc123.jpg"],
    )
    missing_components: List[MissingComponent] = Field(
        default_factory=list,
        description=(
            "Optional list of missing components detected by the AI/CV model. "
            "Omit or pass an empty list if not available."
        ),
    )

    @field_validator("object_type")
    @classmethod
    def strip_whitespace(cls, v: str) -> str:
        """Strip leading/trailing whitespace from object_type."""
        return v.strip()


class ScanRead(BaseModel):
    """
    Schema for returning a scan record from the API.
    Includes all fields, including server-generated ones (id, created_at).
    """
    id: int
    object_type: str
    verdict: VerdictEnum
    confidence: float
    image_url: Optional[str]
    created_at: datetime
    missing_components: List[MissingComponent] = Field(
        default_factory=list,
        description="List of missing components, or empty list if none detected.",
    )

    # 'from_attributes = True' allows Pydantic to read data from a SQLAlchemy
    # ORM object (which uses attribute access) instead of a plain dict.
    # Without this, you'd get a validation error when passing an ORM object.
    model_config = {"from_attributes": True}

    @field_validator("missing_components", mode="before")
    @classmethod
    def coerce_none_to_empty_list(cls, v: Any) -> Any:
        """
        Old rows (inserted before this column existed) will have NULL in the DB.
        We normalise NULL → [] so callers always receive a list, never null.
        """
        return v if v is not None else []


class PaginatedScans(BaseModel):
    """Wrapper around a list of scans that also includes pagination metadata."""
    total: int = Field(description="Total number of scans matching the filters.")
    page: int = Field(description="Current page number (1-indexed).")
    page_size: int = Field(description="Number of items per page.")
    items: List[ScanRead]


# ---------------------------------------------------------------------------
# Stats schemas
# ---------------------------------------------------------------------------

class DailyStat(BaseModel):
    """Aggregate stats for a single day."""
    date: str = Field(description="Date in YYYY-MM-DD format.")
    total: int
    worthy: int
    not_worthy: int
    pass_rate: float = Field(description="Fraction of scans that were worthy (0.0–1.0).")


class SummaryStats(BaseModel):
    """
    Schema for GET /stats/summary response.
    Provides overall counts plus an optional per-day breakdown.
    """
    total_scans: int
    worthy_count: int
    not_worthy_count: int
    pass_rate: float = Field(
        description="Fraction of total scans that passed (worthy / total). "
                    "Returns 0.0 if there are no scans yet."
    )
    # If the caller requests a daily breakdown, this list is populated.
    # Otherwise it's None (omitted from the JSON response).
    daily_breakdown: Optional[List[DailyStat]] = None

    # Summed missing quantities per component name across all scans.
    # Key = component name (e.g. "capacitor"), Value = total units missing.
    # Only present when at least one scan has a non-empty missing_components list.
    missing_component_counts: Optional[Dict[str, int]] = Field(
        default=None,
        description=(
            "Total number of missing units per component name, summed across all scans. "
            "e.g. {\"capacitor\": 12, \"resistor\": 5}. "
            "null when no scans have missing component data."
        ),
    )


# ---------------------------------------------------------------------------
# Health check schema
# ---------------------------------------------------------------------------

class HealthResponse(BaseModel):
    """Schema for GET /health response."""
    status: str = Field(description="'ok' when the service is healthy.")
    database: str = Field(description="'connected' or an error message.")
