"""
schemas.py
----------
Defines Pydantic models for request/response validation and serialization.

Pydantic is separate from SQLAlchemy:
  - SQLAlchemy models (models.py) = the database table definition.
  - Pydantic schemas (this file)  = the shape of JSON in API requests/responses.

Why separate? Because what goes in/out of the API is often different from
what's stored in the DB. For example, 'id' and 'created_at' are DB-generated —
the client shouldn't (and can't) set them, but the API should return them.

Naming convention used here:
  - ScanCreate  = body of a POST /scans request (fields the client sends)
  - ScanRead    = a scan record returned by the API (includes all fields)
  - etc.
"""

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, field_validator


# ---------------------------------------------------------------------------
# Shared enums
# ---------------------------------------------------------------------------

class ObjectTypeEnum(str, Enum):
    """
    Restricts 'object_type' to the 5 PCB boards the AI/CV team supports.
    Any other value will be rejected automatically by Pydantic with a clear
    422 Unprocessable Entity validation error.
    """
    arduino_uno  = "arduino_uno"
    arduino_nano = "arduino_nano"
    esp32        = "esp32"
    raspberry_pi = "raspberry_pi"
    orange_pi    = "orange_pi"


class VerdictEnum(str, Enum):
    """
    Restricts the 'verdict' field to exactly two allowed values.
    Using an Enum instead of a plain string means Pydantic will reject
    any other value automatically and return a clear validation error.
    """
    worthy = "worthy"
    not_worthy = "not_worthy"


# ---------------------------------------------------------------------------
# Missing component schema
# ---------------------------------------------------------------------------

class ComponentLocation(BaseModel):
    """
    Optional location hint for a missing component, supplied by the AI/CV model.

    Two scenarios are possible — and they are independent of each other:
      - label: the silkscreen designator visible on the board (e.g. "R17", "C3").
      - area:  a rough zone described in Bahasa Indonesia when no label is visible
               (e.g. "kiri atas", "dekat port USB", "tengah", "kanan bawah").

    Both fields are optional. The AI/CV model may provide neither, one, or both,
    depending on what it could determine for that specific component.
    """
    label: Optional[str] = Field(
        default=None,
        description="Exact silkscreen designator if visible on the board (e.g. 'R17', 'C3').",
        examples=["R17"],
    )
    area: Optional[str] = Field(
        default=None,
        description=(
            "Rough zone on the board described in Bahasa Indonesia, used when "
            "no exact label is available (e.g. 'kiri atas', 'dekat port USB')."
        ),
        examples=["kiri atas"],
    )

    model_config = {"extra": "ignore"}


class MissingComponent(BaseModel):
    """
    Represents a single missing component detected by the AI/CV model.

    The AI/CV team provides the component name, how many are missing, and
    optionally where on the board the gap is. Extra fields in the payload are
    silently ignored to stay forward-compatible with old client versions.
    """
    name: str = Field(
        ...,
        min_length=1,
        description="Label / name of the missing component, e.g. 'resistor'.",
        examples=["resistor"],
    )
    count: int = Field(
        ...,
        ge=1,
        description="How many of this component are missing (must be at least 1).",
        examples=[2],
    )
    location: Optional[ComponentLocation] = Field(
        default=None,
        description=(
            "Optional location hint for this missing component. "
            "Omit if the AI/CV model could not determine a position."
        ),
    )

    model_config = {
        # Allow extra fields so old payloads (with x/y/confidence) won't cause
        # Pydantic validation errors — those keys are simply discarded.
        "extra": "ignore",
    }


# ---------------------------------------------------------------------------
# Scan schemas
# ---------------------------------------------------------------------------

class ScanCreate(BaseModel):
    """
    Schema for POST /scans — the body the device/inference script sends.
    Only includes fields that the client provides; id and created_at are
    generated by the server.
    """
    object_type: ObjectTypeEnum = Field(
        ...,  # '...' means this field is required (no default).
        description=(
            "Type of PCB board scanned. Must be one of the supported board types: "
            "'arduino_uno', 'arduino_nano', 'esp32', 'raspberry_pi', 'orange_pi'. "
            "Any other value will be rejected with a 422 validation error."
        ),
        examples=["esp32"],
    )
    verdict: VerdictEnum = Field(
        ...,
        description="AI model verdict: 'worthy' or 'not_worthy'.",
    )
    confidence: float = Field(
        ...,
        ge=0.0,  # ge = "greater than or equal to"
        le=1.0,  # le = "less than or equal to"
        description="Model confidence score between 0.0 and 1.0.",
        examples=[0.97],
    )
    image_url: Optional[str] = Field(
        default=None,
        description="Optional URL pointing to the scan image.",
        examples=["https://storage.example.com/scans/abc123.jpg"],
    )
    missing_components: List[MissingComponent] = Field(
        default_factory=list,
        description=(
            "Optional list of missing components detected by the AI/CV model. "
            "Omit or pass an empty list if not available. Each item may include "
            "an optional 'location' object with a silkscreen label and/or area zone."
        ),
    )


class ScanRead(BaseModel):
    """
    Schema for returning a scan record from the API.
    Includes all fields, including server-generated ones (id, created_at).
    """
    id: int
    object_type: ObjectTypeEnum
    verdict: VerdictEnum
    confidence: float
    image_url: Optional[str]
    created_at: datetime
    missing_components: List[MissingComponent] = Field(
        default_factory=list,
        description=(
            "List of missing components, or empty list if none detected. "
            "Each item may include an optional 'location' object."
        ),
    )

    # 'from_attributes = True' allows Pydantic to read data from a SQLAlchemy
    # ORM object (which uses attribute access) instead of a plain dict.
    # Without this, you'd get a validation error when passing an ORM object.
    model_config = {"from_attributes": True}

    @field_validator("missing_components", mode="before")
    @classmethod
    def coerce_none_to_empty_list(cls, v: Any) -> Any:
        """
        Old rows (inserted before this column existed) will have NULL in the DB.
        We normalise NULL → [] so callers always receive a list, never null.
        """
        return v if v is not None else []


class PaginatedScans(BaseModel):
    """Wrapper around a list of scans that also includes pagination metadata."""
    total: int = Field(description="Total number of scans matching the filters.")
    page: int = Field(description="Current page number (1-indexed).")
    page_size: int = Field(description="Number of items per page.")
    items: List[ScanRead]


# ---------------------------------------------------------------------------
# Stats schemas
# ---------------------------------------------------------------------------

class DailyStat(BaseModel):
    """Aggregate stats for a single day."""
    date: str = Field(description="Date in YYYY-MM-DD format.")
    total: int
    worthy: int
    not_worthy: int
    pass_rate: float = Field(description="Fraction of scans that were worthy (0.0–1.0).")


class SummaryStats(BaseModel):
    """
    Schema for GET /stats/summary response.
    Provides overall counts plus an optional per-day breakdown.
    """
    total_scans: int
    worthy_count: int
    not_worthy_count: int
    pass_rate: float = Field(
        description="Fraction of total scans that passed (worthy / total). "
                    "Returns 0.0 if there are no scans yet."
    )
    # If the caller requests a daily breakdown, this list is populated.
    # Otherwise it's None (omitted from the JSON response).
    daily_breakdown: Optional[List[DailyStat]] = None

    # Summed missing quantities per component name across all scans.
    # Key = component name (e.g. "capacitor"), Value = total units missing.
    # Only present when at least one scan has a non-empty missing_components list.
    missing_component_counts: Optional[Dict[str, int]] = Field(
        default=None,
        description=(
            "Total number of missing units per component name, summed across all scans. "
            "e.g. {\"capacitor\": 12, \"resistor\": 5}. "
            "null when no scans have missing component data."
        ),
    )


# ---------------------------------------------------------------------------
# Health check schema
# ---------------------------------------------------------------------------

class HealthResponse(BaseModel):
    """Schema for GET /health response."""
    status: str = Field(description="'ok' when the service is healthy.")
    database: str = Field(description="'connected' or an error message.")
